### PR TITLE
Refactor plugin to work with Errbit v0.4.0 API

### PR DESCRIPTION
**Pull request by jesenko**
API for issue tracker plugins was changed significantly in Errbit v0.4.0. This PR refactors redmine plugin to the new API.

### CODE REVIEW

**Comment by luxflux** [comment]
This works for us, what about merging it?

**Comment by stevecrozz** [comment]
Looks good to me. Thanks!

**Comment by stevecrozz** [comment]
Just published v0.4.0 https://rubygems.org/gems/errbit_redmine_plugin/versions/0.4.0

**Comment by felixbuenemann** [comment]
@jesenko How are templates configured now? This change causes the issue template to be rendered as markdown, but our redmine is using textile. I found `app/views/issue_trackers/issue.md.erb` in errbit, but how would the issue tracker plugin tell errbit to use a different template?

**Comment by felixbuenemann** [comment]
Answering my own question: Looking at errbit/errbit#840 is looks like the issue tracker blugin should implement `render_body_args` which returns an array of the template path and options, something like:

``` ruby
 ['issue_trackers/issue', formats: [:md]]
```

Given that newer versions of redmine support either markdown or textile (but not at the same time), this would have to be configurable.

**Pull request merged**
